spring.application.name=order-service
server.port=8081

spring.datasource.url=jdbc:h2:mem:orderdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

integration.payment.url=http://localhost:8082

spring.cloud.openfeign.client.config.payment-service-client.connectTimeout=1000
spring.cloud.openfeign.client.config.payment-service-client.readTimeout=1000

management.health.circuitbreakers.enabled=true
management.endpoints.web.exposure.include=health,circuitbreakers,circuitbreakerevents,retries,retryevents,ratelimiters,ratelimiterevents
management.endpoint.health.show-details=always

resilience4j.circuitbreaker.instances.serverController.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.serverController.slidingWindowSize=5
resilience4j.circuitbreaker.instances.serverController.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.serverController.failureRateThreshold=50
resilience4j.circuitbreaker.instances.serverController.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.serverController.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.serverController.ignoreExceptions=com.example.orderservice.service.ResourceNotFoundException

resilience4j.circuitbreaker.instances.paymentClient.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.instances.paymentClient.slidingWindowSize=5
resilience4j.circuitbreaker.instances.paymentClient.minimumNumberOfCalls=3
resilience4j.circuitbreaker.instances.paymentClient.failureRateThreshold=50
resilience4j.circuitbreaker.instances.paymentClient.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.paymentClient.permittedNumberOfCallsInHalfOpenState=2
resilience4j.circuitbreaker.instances.paymentClient.ignoreExceptions=com.example.orderservice.service.ResourceNotFoundException

resilience4j.retry.instances.paymentClient.maxAttempts=3
resilience4j.retry.instances.paymentClient.waitDuration=500ms
resilience4j.retry.instances.paymentClient.retryExceptions=feign.RetryableException,feign.FeignException$InternalServerError,feign.FeignException$ServiceUnavailable,feign.FeignException$GatewayTimeout
resilience4j.retry.instances.paymentClient.ignoreExceptions=com.example.orderservice.service.ResourceNotFoundException

resilience4j.ratelimiter.instances.paymentClient.limitForPeriod=2
resilience4j.ratelimiter.instances.paymentClient.limitRefreshPeriod=10s
resilience4j.ratelimiter.instances.paymentClient.timeoutDuration=0

logging.level.io.github.resilience4j.retry=DEBUG
logging.level.io.github.resilience4j.ratelimiter=DEBUG
logging.level.com.example.orderservice.integration.payment=INFO
